include/indexstore/IndexStoreCXX.h
Also only use the '*_f' functions across platforms, for simplicity.
=> [IndexStoreCXX.h] Fix the crashing issue with using the '*_f' functions

Package.swift, include/indexstore/IndexStoreCXX.h, lib/Support/Logging.cpp
Apparently we cannot have nice things like c++14.
=> Fix build on Ubuntu 14.04

Utilities/build-script-helper.py
(cherry picked from commit a7fa38fb09c3a684c728f2456840329c7fd0330d)
=> [5.1] [SR-11164] Use the toolchain's Block.h

Sources/ISDBTibs/TibsBuilder.swift
After ninja was updated, started seeing extra quote characters around these paths which interfered with tests.
=> [test] Attempt to fix quoting issue on bot

Sources/ISDBTibs/TibsToolchain.swift
Windows (without msys) doesn't have `where`, instead, use the native `which`
to locate tools.
=> Use where.exe on Windows instead of which

Sources/ISDBTestSupport/TibsTestWorkspace.swift
Useful if you want to test closing and reopening the same DB.
=> [tibs] Allow tibs workspace to preserve tmpDir on deinit

README.md
Update README to add Some Example Users
=> Update README to add Example Users

lib/Index/IndexDatastore.cpp
This is because processing populates the database and C++ exceptions can be thrown; libIndexStore builds with -fno-exceptions so we cannot be throwing C++ exceptions from inside its frames.
rdar://55930012
=> Collect the newly discovered records and process them outside of the libIndexStore callback

Sources/ISDBTibs/TibsToolchain.swift
The previous check for apple-clang, swift-clang, etc. was failing on
released toolchains, since they don't contain the repo name, and on
clones of the repo that didn't match the pattern.
Check clang -help for index store support. It would be better to check
that `clang -index-store-path /dev/null --version` does not produce an
error, but unfortunately older versions of clang accepted
`-index-store-path` due to the existince of a `-i` option that has since
been removed. While we could check a full compile command, I have not
found a robust command that detects index support without also doing I/O
in the index directory when it succeeds. To avoid I/O, we check -help.
=> [tibs] Detect clang index support using -help instead of --version

Sources/IndexStoreDB/IndexStoreDB.swift, Tests/INPUTS/MainFiles/main1.c, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/FilePathIndex.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Support/Path.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FilePathIndex.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp
master: https://github.com/apple/indexstore-db/pull/92
=> [5.3][Index] Add APIs to provide the recorded #includes of a unit file

Utilities/build-script-helper.py
master: https://github.com/apple/indexstore-db/pull/95
=> [5.3][build-script-helper] Always do a clean build, to workaround an incremental build bug in swiftpm

Sources/ISDBTibs/TibsToolchain.swift
Cherry-pick #79 to 5.3
* Explanation: The way our unit tests detect "index while building" support was brittle in practice, which could cause tests to fail spuriously with (a) a toolchain built locally, depending on how your forks are setup, or (b) when using a final released toolchain from swift.org (e.g. `5.2-RELEASE`).  The fix is to check for `-index-store-path` in `-help` instead of trying to infer whether the `--version` output comes from a swift-clang fork.
* Scope: Test-only change.
* Risk: Low. This is test-only, and is not tied in with anything else.
* Reviewer: @akyrtzi
* Testing: Regression tests pass.
* Bug: rdar://63023189
=> [5.3] [tibs] Detect clang index support using -help instead of --version

Sources/ISDBTestSupport/TibsTestWorkspace.swift
This reverts commit 5690edfb82ac3b77ccf4cbe23789b462ca3e8ee4.
The underlying issue SR-12569 has been fixed.
=> Revert "[test] Workaround an issue with createDirectory on Linux"

lib/Database/Database.cpp
`GetCurrentProcess` provides a process _handle_ (which for current
process is a pseudo-handle of `-1`).  Use `GetCurrentProcessId` which is
the moral equivalent to `getpid`.
=> Database: correct the PID recording on Windows

Tests/IndexStoreDBTests/IndexTests.swift
=> [IndexTests] Re-enable `testOutOfDateEvent()` and add a `sleep` call to make it deterministic

Utilities/build-script-helper.py, Utilities/import-llvm
(cherry picked from commit 7adf2b1c2b74567eb7fe9e55e837eee6a9ad5cc5)
=> [5.7] Update build-script-helper.py to Python 3

Sources/IndexStoreDB/Symbol.swift
Needed for https://github.com/apple/sourcekit-lsp/pull/1166
=> Make `Symbol` conform to `Hashable`

Sources/IndexStoreDB/IndexStoreDB.swift
This is simply an update to #211 based on feedback given in the similar swiftlang/swift-package-manager#7752.
=> Import new Bionic module from Android overlay instead

README.md
=> Update README.md for apple -> swiftlang move of llvm-project

Utilities/build-script-helper.py
Use the same approach that we’ve taken in SourceKit-LSP to capture more actionable output.
=> Re-run tests serially if parallel testing failed
