swiftlang/indexstore-db

include/IndexStoreDB/Core/Symbol.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
The indexstoredb_* functions are returning pointers to temporary strings.
=> [CIndexStoreDB] Fix use after free issue with temporary strings

Package.swift
SwiftPM doesn't protect us from module name conflicts, and this happens
to collide with llbuild's names. Add a prefix to workaround.
See https://bugs.swift.org/browse/SR-9292
=> [llvm] Add IndexStoreDB_ prefix to LLVMSupport to avoid conflicts

include/llvm/Config/config.h
This API is available in macOS 10.13, but since this configuration is
fixed, we should be conservative. In practice the only effect this has
is to fix a warning while building this code on macOS, because the only
function that uses futimens is setLastModificationAndAccessTime, which
is not used anywhere in indexstore-db.
=> [config] Disable futimens to fix backward deployment issue

Utilities/build-script-helper.py
This is a lightweight wrapper for `swift build` and `swift test` to
facilitate building indexstore-db along with a swift toolchain using the
swift `build-script`.
=> [build-script] Add build-script-helper.py

include/IndexStoreDB/Index/IndexSystemDelegate.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp
Previously if there were multiple headers that got out-of-date and they were all included by the same main file, it would trigger a single notification for that main file. With these changes there will be notifications for each file.
This allows clients to get the full information of what needs to get updated and they get the responsibility for doing any kind of coalescing they want.
=> [IndexDatastore] For the out-of-date trigger notifications report all the out-of-date files without any coalescing

include/IndexStoreDB/Core/Symbol.h, include/IndexStoreDB/Database/ImportTransaction.h, include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Database/UnitInfo.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/IndexSystemDelegate.h, include/IndexStoreDB/Index/StoreUnitInfo.h, lib/Database/Database.cpp, lib/Database/DatabaseImpl.h, lib/Database/ImportTransaction.cpp, lib/Database/ImportTransactionImpl.h, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp, lib/Index/SymbolIndex.cpp
The latest version of llvm no longer has TimeValue.h, so this replaces uses
with TimePoint and std::chrono.
I'd like to start porting this to Windows and as part of that, I need to pull in the Windows headers which means updating the llvm support libraries that are part of indexstore-db.
=> Remove all Uses of TimeValue

include/IndexStoreDB/Database/Database.h, include/IndexStoreDB/Database/DatabaseError.h, include/IndexStoreDB/Database/ImportTransaction.h, include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Index/IndexStoreLibraryProvider.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/IndexSystemDelegate.h, include/IndexStoreDB/Support/Concurrency.h, include/IndexStoreDB/Support/FilePathWatcher.h, include/IndexStoreDB/Support/Logging.h, include/IndexStoreDB/Support/Path.h, include/IndexStoreDB/Support/PatternMatching.h, include/IndexStoreDB/Support/Visibility.h
LLVM_EXPORT no longer exists in llvm, remove it in preparation to pull in a new version
=> Remove LLVM_EXPORT references

lib/Index/IndexDatastore.cpp
This is useful to avoid doing a lot of parallel CPU and I/O work when opening multiple workspaces.
It also allows the unit processing to stop when the workspace closes, instead of continuing until all units have been processed.
rdar://36996503
=> [Index] Use a single global serial queue for registration of units

lib/Index/IndexDatastore.cpp
This introduces a const variable to control the max number of batches, instead of only being able to process one at a time.
=> [Index] For registering units process them in batches of maximum 10 at a time

lib/Index/IndexDatastore.cpp
It wasn't taking into account processing the initial units as multiple batches and the case where the data store directory has no units.
=> [IndexDatastore] Ensure `IndexDatastore::waitUntilDoneInitializing()` works properly

include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/SymbolDataProvider.h, include/IndexStoreDB/Index/SymbolIndex.h, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/IndexSystem.cpp, lib/Index/StoreSymbolRecord.cpp, lib/Index/StoreSymbolRecord.h, lib/Index/SymbolIndex.cpp
This is useful for retrieving all the unit test class/method occurrences that are referenced from a set of output file paths and their associated units.
=> [Index] Introduce IndexSystem::foreachUnitTestSymbolReferencedByOutputPaths()

include/IndexStoreDB/Database/ReadTransaction.h, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/SymbolIndex.cpp
Previously it was returning the unit with the most recent modification time, and if that unit was filtered-out by SymbolIndexImpl::createProviderForCode()
then the whole provider would be ignored, which is incorrect because there could be other units for the same provider that are eligible.
This change moves the filtering into the `ReadTransaction`'s call.
=> [Database] For ReadTransaction::getProviderFileCodeReferences() make sure to filter the units properly

include/IndexStoreDB/Database/ImportTransaction.h, include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Database/UnitInfo.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/StoreUnitInfo.h, include/IndexStoreDB/Index/SymbolIndex.h, lib/Database/Database.cpp, lib/Database/DatabaseImpl.h, lib/Database/ImportTransaction.cpp, lib/Database/ImportTransactionImpl.h, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp, lib/Index/SymbolIndex.cpp
This allows the client to be much more efficient for handling unit test symbol changes.
=> Keep track and report the unit files that contain test symbols

include/IndexStoreDB/Database/Database.h, lib/Database/Database.cpp, lib/Index/IndexStoreLibraryProvider.cpp, lib/Support/Path.cpp
This allows IndexStoreDB to build on Windows.
Once the other PRs go in, this enables compilation on Windows. I have some CMake locally which I've been using to build this, but it should work just as well with SwiftPM when that is ready on Windows.
=> Windows Port

lib/Index/IndexDatastore.cpp
https://bugs.swift.org/browse/SR-10319
=> Workaround corelibs-libdispatch crash SR-10319

lib/Index/IndexDatastore.cpp
https://github.com/apple/indexstore-db/pull/27 for swift-5.1-branch
---
https://bugs.swift.org/browse/SR-10319
=> [5.1] Workaround corelibs-libdispatch crash SR-10319

Sources/IndexStoreDB/IndexStoreDB.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
This can be used in lsp projects to find
all symbols in a workspace that match a string.
https://bugs.swift.org/browse/SR-10806
=> Add ability to find symbols by name

Sources/IndexStoreDB/IndexStoreDB.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
Add kind property to Symbol
Add forEachRelation of occurrence function
Based on discussions in [workspace/symbol PR](https://github.com/apple/sourcekit-lsp/pull/118) in apple/sourcekit-lsp.
=> Add SymbolRelation class with roles and symbols

Utilities/build-script-helper.py
For now, just thread ninja_bin through as an environment variable.
Future commits will make use of this during testing. Also pass the
toolchain path and remove unnecessary differences with the sourcekit-lsp
build-script-helper script.
=> [build-script] Accept --ninja-bin and sync with sourcekit's build-script-helper

Documentation/Development.md, Documentation/Tibs.md, README.md
Add a new `Documentation/Development.md` file to serve as an index of documentation about development of the indexer, and start out by filling in information about how to write tests using the new test infrastructure.  Also document the Tibs build system.
=> [docs] Add documentation about writing tests for IndexStoreDB

Sources/ISDBTestSupport/TestLocationScanner.swift, Tests/IndexStoreDBTests/LocationScannerTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift
Using a leading '<', we can now specify a location ending at the comment
instead of after it.  For example,
```swift
/*a:start*/abc/*<a:end*/
//         ^  ^
//   a:start  a:end
```
This is useful for forming source ranges.
=> [test] Add syntax for marking test location ending at comment

Sources/ISDBTestSupport/TestLocation.swift, Sources/ISDBTestSupport/TestLocationScanner.swift, Tests/IndexStoreDBTests/LocationScannerTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift
Previously we were using character index, which doesn't match what any
clients want. LSP will generally want to compare to the utf16 index,
while anything else probably uses utf8.
=> [test] Split TestLocation column into explicit utf8/utf16 indices

Sources/ISDBTibs/TibsBuilder.swift, Sources/ISDBTibs/TibsResolvedTarget.swift, Tests/ISDBTibsTests/TibsCompilationDatabaseTests.swift, Tests/ISDBTibsTests/TibsResolutionTests.swift
When compiling with toolchains that do not include the swift stdlib
(e.g. the Xcode toolchain), we need the SDK path to be explicitly passed
as an argument.
=> [tibs] Add -sdk to swift compiles on macOS

include/CIndexStoreDB/CIndexStoreDB.h
The `INDEXSTORE_PUBLIC` macro was guarding based on `_MSC_VER` which is
a check for MSVC's compiler which is incorrect.  This annotation has
nothing to do with the MSVC compiler but rather the PE/COFF file format.
Adjust that to `_WIN32` as an alias for Windows.
Furthermore, correct the annotation - the functions should be given
dllexport storage when building IndexStoreDB, and dllimport storage when
building code which uses IndexStoreDB (unless it is statically built).
=> CIndexStoreDB: correct dllstorage annotation

include/indexstore/indexstore_functions.h
The dllstorage appertains to function and variable (declaration,
applied to definitions).  The usage here was to members of a type
definition which does not make sense.  This has no change as the
annotation is ignored with a warning.
=> IndexStore: correct dllstorage attributes (NFC)

Sources/ISDBTibs/Process.swift, Sources/ISDBTibs/TibsBuilder.swift, Sources/ISDBTibs/TibsToolchain.swift
Fix warnings by using the non-deprecated APIs, and while we're at it
consolidate all the uses into a single place that checks the result and
collects stdout. Inspired by SwiftPM's checkNonZeroExit.
=> [tibs] Consolidate uses of Process and fix warnings

Sources/IndexStoreDB/Symbol.swift, Sources/IndexStoreDB/SymbolOccurrence.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
These objects are now valid only during the callbacks that provide them
from the index. Since we already converted them immediately, this didn't
impact the Swift code except to remove the indexstoredb_release calls
for these. I updated the documentation to indicate the new lifetime.
Incidentally, relation was using the make_object machinery even though
it was documented to only live for the callback, so this fixes a leak of
relations.
=> Remove unnecessary refcounting and allocation for symbol, occurrence, relation

Tests/IndexStoreDBTests/IndexStoreDBTests.swift
Windows is able to create the directory `/nope` since a leading `/`
indications a drive relative path. Instead, use `/nope:` which is
invalid both on POSIX and Windows.
=> Use a Path that is Also Invalid on Windows in testErrors

Sources/ISDBTibs/TibsBuilder.swift
On Windows, Ninja outputs CRLF instead of just an LF.
=> Add Support for CRLF when Parsing Ninja Output

Tests/INPUTS/MixedLangTarget/bridging-header.h
Windows doesn't support `#import` and using `#include` instead doesn't
affect this test case.
=> Use include instead of import

Sources/ISDBTibs/TibsToolchain.swift
- Shared libs have a .dll extension
- dlls are typically store in bin along side the executables on Windows
=> Search for Shared Libraries Properly on Windows

Sources/ISDBTibs/Makefile.swift, Sources/tibs/main.swift, Tests/ISDBTibsTests/MiscTests.swift, Tests/ISDBTibsTests/XCTestManifests.swift
In a Makefile, spaces can be escaped by a preceeding backslash. Rather
than using string.split, iterate through the string keeping track of the
previous character.
=> Handle Spaces in Makefile Parsing

Sources/ISDBTibs/TibsBuilder.swift
- Ninja requires that `:`s in filenames be escaped as `$:`
- Explicitly call cmd.exe /C on Windows
- In addition, escape spaces for the command that we pass to cmd.exe
I stole the command line quoting verbatim from the one [I wrote for Foundation.]( https://github.com/apple/swift-corelibs-foundation/blob/c5c35c1a59b0a9a05b2e1ffbf8a7bab0a3e59baa/Foundation/Process.swift#L106)
=> Fix Ninja Output for Windows

Sources/ISDBTibs/TibsToolchain.swift
We saw a test for incremental build fail once in CI. I'm not sure what
exactly the behaviour on that bot is, but in Docker I can reproduce a
timestamp resolution of a bit more than 10 ms. So bump the minimum to 20
ms to workaround.
rdar://54419544
=> [test] Bump minimum delay for incremental build after change

Sources/ISDBTibs/TibsToolchain.swift
We saw a test for incremental build fail once in CI. I'm not sure what
exactly the behaviour on that bot is, but in Docker I can reproduce a
timestamp resolution of a bit more than 10 ms. So bump the minimum to 20
ms to workaround.
rdar://54419544
=> [5.1] [test] Bump minimum delay for incremental build after change

Sources/ISDBTibs/TibsToolchain.swift
My previous change to add a minimum sleep time when testing modified
sources was accidentally broken because I had `if usec > minimum` - that
was only intended to silence the warning, not disable the sleep itself.
When I tested this originally I must have gotten lucky; it seems to fail
1/20 or so in Docker for me. After this commit, I haven't seen any
failures after several hundred runs.
[SR-11356](https://bugs.swift.org/browse/SR-11356)
rdar://54612870
=> [test] Fix minimum sleep change

Sources/IndexStoreDB/IndexStoreDB.swift
We accidentally added a conformance to UnsafeMutablePointer, since the
error is actually a C typedef of a void pointer. Luckily we don't care
about the conformance, only the concrete implementation here.
=> Fix crash when printing UnsafeMutableRawPointer

CMakeLists.txt, Sources/CMakeLists.txt, Sources/IndexStoreDB/CMakeLists.txt, cmake/modules/CMakeLists.txt, cmake/modules/IndexStoreDBConfig.cmake.in, cmake/modules/SwiftSupport.cmake, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CMakeLists.txt, lib/CMakeLists.txt, lib/Core/CMakeLists.txt, lib/Database/CMakeLists.txt, lib/Index/CMakeLists.txt, lib/LLVMSupport/CMakeLists.txt, lib/Support/CMakeLists.txt
Add a CMake build system to enable building this on platforms where it is
not currently viable to build using swift-package-manager.  This is
intended to be a mechanism to enable bootstrapping SourceKit-LSP for
platforms such as Windows.
=> build: add CMake build system

Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
When initializing the database, allow waiting for the initial scan to
finish. The existing behaviour is useful for tools like an editor where
you want to return as quickly as possible and don't need to wait for the
data to populate, but for something like a command-line tool making a
query where it expects the data to be ready we needed a way to finish
loading before continuing.
=> Pass through waitUntilDoneInitializing option in Index init

Sources/ISDBTibs/TibsToolchain.swift, Utilities/import-llvm.d/include/llvm/Config/config.h, include/llvm/Config/config.h, lib/Database/lmdb/mdb.c
I used this pull to build and test natively on Android in [the Termux app](https://termux.com/), all tests passing.
=> Android: add support in TibsToolchain, LLVM config, and fix lmdb ifdefs

include/indexstore/IndexStoreCXX.h, include/indexstore/indexstore_functions.h, lib/Index/indexstore_functions.def
This was removed from the implementation. While this is an ABI break,
it's one that we may be able to accept since we aren't using this
function for anything in practice.
rdar://58836941
=> [libindexstore] Remove indexstore_unit_event_get_modification_time

Sources/ISDBTestSupport/TibsTestWorkspace.swift, Tests/IndexStoreDBTests/IndexStoreDBTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, lib/Index/IndexSystem.cpp
We already do this for the database, so add the store as well. This allows you to open the index before it has been populated.
=> Create the index store path if it does not exist

Sources/ISDBTestSupport/TibsTestWorkspace.swift, Tests/IndexStoreDBTests/IndexStoreDBTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, lib/Index/IndexSystem.cpp
Reverts apple/indexstore-db#65
This [breaks CI](https://ci.swift.org/job/oss-swift-master-rebranch-incremental-RA-linux-ubuntu-16_04-long-test/56/console) for master-rebranch.
```bash
inotify_add_watch() error: No such file or directory
```
It appears that DirectoryWatcher no longer creates the directory to be watched, so while there will be `indexstore`, there will not be `indexstore/vN/units` that it is expecting.  This should get fixed in clang, since we should not be guessing what the structure if from outside libIndexStore.
=> Revert "Create the index store path if it does not exist"

Sources/ISDBTestSupport/TibsTestWorkspace.swift, Tests/IndexStoreDBTests/IndexStoreDBTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, lib/Index/IndexSystem.cpp
Reapply apple/indexstore-db#65.  Depends on  https://github.com/apple/llvm-project/pull/710 being merged it into `swift/master-rebranch`.
---
We already do this for the database, so add the store as well. This allows you to open the index before it has been populated.
=> Reapply "Create the index store path if it does not exist"

lib/Database/lmdb/lmdb.h, lib/Database/lmdb/mdb.c, lib/Database/lmdb/midl.c, lib/Database/lmdb/midl.h
A summary of the more interesting changes:
* `mdb_env` flag `MDB_PREVMETA` has been renamed to `MDB_PREVSNAPSHOT` and support for it has improved. For a hint on how it can be useful see http://www.openldap.org/its/index.cgi/Software%20Enhancements?id=8704 :
Generally, running LMDB in NOSYNC mode means all integrity guarantees are gone,
in even of a system crash. However, if some other thread runs mdb_env_sync
periodically it's possible that the older DB state is still consistent, even if
slightly out of date. I have always intended to add an env flag for using the
older meta page, to potentially access a DB even after the latest txn snapshot
was corrupted.
AFAICT we could utilize this by periodically calling `mdb_env_sync` and after a crash open the database using `MDB_PREVSNAPSHOT`, …
=> [lmdb] Update LMDB to to latest version from upstream

Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift
There are scenarios where one wants to iterate through the list of all the symbols in the index. Such functionality exists in the underlying lower-level library. 
This PR makes that functionality available to `indexstore-db` users.
=> Expose the name of every symbol in the index 

lib/Index/IndexDatastore.cpp
This is because processing populates the database and C++ exceptions can be thrown; libIndexStore builds with -fno-exceptions so we cannot be throwing C++ exceptions from inside its frames.
rdar://60611975
=> Collect the dependency info and process them outside of the libIndexStore callback

lib/CIndexStoreDB/CMakeLists.txt, lib/Index/CMakeLists.txt, lib/LLVMSupport/CMakeLists.txt
Windows can still be finicky with symbolic links.  This adjusts the
include paths to allow building without relying on them.
Additionally, make the include path for `indexstore` public so that
users of it will implicitly get its headers.  Lastly, adjust the linking
for CIndexStore to use `PUBLIC` for `indexstore` to allow the header
include paths to be transitively included.  This mirrors the behaviour
of swift-package-manager.
This allows IndexStoreDB to be built on Windows again.
=> build: allow building with CMake without symlinks

Utilities/build-script-helper.py
It's slightly faster and it helps supress the test output when tests
succeed (which avoids false positives in Jenkins' error regexes).
=> [build-script] Add --parallel to supress output on success

Sources/ISDBTestSupport/TibsTestWorkspace.swift
Looks like createDirectory can fail spuriously if run in parallel with a
common parent path missing. Will file a bug on corelibs-foundation, but
for now workaround to avoid test failures.
rdar://61545973
=> [test] Workaround an issue with createDirectory on Linux

Sources/ISDBTibs/TibsToolchain.swift, Utilities/build-script-helper.py
Because of a bug upstream in the main build-script, the install prefix set by the user wasn't being passed in to this repo and these files assumed it to be `/usr`. This pull removes that assumption and has the main build-script pass an install prefix appended to the toolchain path instead, apple/swift#30565.
=> [build-script][test] Remove hard-coded install prefix of /usr and pass it in instead

lib/Index/IndexDatastore.cpp
Store the path of the file triggering an out-of-date check once in the
array of checks, rather than once for every unit. For headers included
by many unit files this was causing us to use several GB just for this
single std::vector.
rdar://53835770
=> Reduce memory usage in onFSEvent callback

Sources/ISDBTestSupport/TibsTestWorkspace.swift, Sources/ISDBTibs/TibsBuilder.swift, Sources/ISDBTibs/TibsResolvedTarget.swift, Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FileVisibilityChecker.cpp, lib/Index/FileVisibilityChecker.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp
The benefits of this approach is that it allows the datastore to ignore leftover unit files so it can both improve performance and correctness by not taking into account stale data.
rdar://61899059
=> [Index] Provide capability for the client to explicitly specify the list of output unit files for the datastore

lib/Index/IndexDatastore.cpp
Argyrios suggested switching to std::string, since CanonicalFilePath
contains a SmallString<128>.
rdar://53835770
=> Additional memory savings for onFSEvent

Sources/ISDBTibs/TibsToolchain.swift, Utilities/build-script-helper.py
Cherry-pick #75 to 5.3 to fix the CI build
=> [5.3] [build-script][test] Remove hard-coded install prefix of /usr and pass it in instead

lib/Index/IndexDatastore.cpp
Cherry-pick #84 and #86 to 5.3
----
Store the path of the file triggering an out-of-date check once in the
array of checks, rather than once for every unit. For headers included
by many unit files this was causing us to use several GB just for this
single std::vector.
rdar://53835770
=> [5.3] Reduce memory usage in onFSEvent callback

include/IndexStoreDB/Index/IndexSystem.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp
This mechanism is disabled by default for the CIndexStoreDB API because the out-of-date notifications are not exposed at all, so the mechanism is taking CPU & memory unnecessarily.
=> [IndexDatastore] Provide an option to disable the file-out-of-date notification mechanism

lib/Index/IndexDatastore.cpp
It is normal to setup the list of units before the data is generated.
=> [IndexDataStore] Reduce logging priority for missing units when in explicit-out-units mode

include/IndexStoreDB/Database/IDCode.h
Discovered this while building under Linux
=> Implicit use of <cstdint.h> fails with Clang 10

Sources/ISDBTestSupport/TibsTestWorkspace.swift, Sources/ISDBTibs/TibsBuilder.swift, Sources/ISDBTibs/TibsResolvedTarget.swift, Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FileVisibilityChecker.cpp, lib/Index/FileVisibilityChecker.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp
master:
https://github.com/apple/indexstore-db/pull/83
https://github.com/apple/indexstore-db/pull/88
https://github.com/apple/indexstore-db/pull/89
=> [5.3] Cherry-picks for options to explicitly control units and disable out-of-date monitoring

Sources/IndexStoreDB/IndexStoreDB.swift, Tests/INPUTS/MainFiles/main1.c, Tests/IndexStoreDBTests/IndexTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/FilePathIndex.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Support/Path.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FilePathIndex.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp
This is second attempt, after I reverted due to bot failures that were not shown in PR testing for first attempt.
=> [Index] Add APIs to provide the recorded #includes of a unit file

Sources/IndexStoreDB/CMakeLists.txt, Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/IndexStoreDBError.swift, Sources/IndexStoreDB/Symbol.swift, Sources/IndexStoreDB/SymbolLocation.swift, Sources/IndexStoreDB/SymbolOccurrence.swift, Sources/IndexStoreDB/SymbolRole.swift
This include path is needed to build SourceKit-LSP.
=> build: add CIndexStoreDB to the interface includes

include/IndexStoreDB/Index/IndexSystem.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp
After we added processUnitsAndWait() as a separte entry point that
ultimately called the onFilesChange() method, it created a race on the
DoneInitState, which was accessed directly in the unit event callback
before jumping to the unit processing queue. Simplify that logic and fix
the race by using processUnitsAndWait() during initialization if we
desire waiting, and get rid of DoneInitState.
The previous approach was more flexible about allowing you to wait at an
arbitrary point after creating the IndexDatastore, but in practice we
were not using that ability, and it made it harder to understand the
synchronization required.
=> [tsan] Fix a race during processUnitsAndWait()

Sources/IndexStoreDB/CMakeLists.txt, lib/CIndexStoreDB/CMakeLists.txt, lib/Database/CMakeLists.txt, lib/Index/CMakeLists.txt, lib/Support/CMakeLists.txt
These come from the SDK and we rely on autolinking. Fixes incorrect
-ldispatch and -lFoundation linker flags.
=> [cmake] Fix linking of Foundation and dispatch on Darwin

Sources/IndexStoreDB/IndexDelegate.swift, Sources/IndexStoreDB/IndexStoreDB.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/CIndexStoreDB/CIndexStoreDB_Internal.h, include/IndexStoreDB/Index/IndexSystem.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexSystem.cpp
Add hooks to add a new delegate to an existing IndexSystem and wrap it with a fresh IndexStoreDB.
=> Add the ability to re-wrap an existing index

Sources/ISDBTibs/TibsToolchain.swift
The previous check for apple-clang, swift-clang, etc. was failing on
released toolchains, since they don't contain the repo name, and on
clones of the repo that didn't match the pattern.
Check clang -help for index store support. It would be better to check
that `clang -index-store-path /dev/null --version` does not produce an
error, but unfortunately older versions of clang accepted
`-index-store-path` due to the existince of a `-i` option that has since
been removed. While we could check a full compile command, I have not
found a robust command that detects index support without also doing I/O
in the index directory when it succeeds. To avoid I/O, we check -help.
=> [5.2] [tibs] Detect clang index support using -help instead of --version

Tests/INPUTS/SingleUnit/main.c, Tests/INPUTS/SingleUnit/project.json, Tests/IndexStoreDBTests/IndexStoreDBTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, Utilities/build-script-helper.py, lib/Database/Database.cpp, lib/Database/DatabaseImpl.h
This is intended to protect against a crash that can occur if trying to use the same lmdb database path from separate wrapper instances.
rdar://39235399
=> [Database] Make the database path unique to the specific lmdb wrapper instance

Tests/INPUTS/SingleUnit/main.c, Tests/INPUTS/SingleUnit/project.json, Tests/IndexStoreDBTests/IndexStoreDBTests.swift, Tests/IndexStoreDBTests/XCTestManifests.swift, lib/Database/Database.cpp, lib/Database/DatabaseImpl.h
This is intended to protect against a crash that can occur if trying to use the same lmdb database path from separate wrapper instances.
rdar://39235399
master: https://github.com/apple/indexstore-db/pull/107
=> [5.3][Database] Make the database path unique to the specific lmdb wrapper instance

Package.swift, lib/Index/IndexSystem.cpp
All calls to `processingCompleted` are called from the unit processing queue, but `processingAddedPending` can be called from other queues, including an arbitrary queue in the case of `addUnitOutFilePaths` and `removeUnitOutFilePaths`.
The result is that if there is a session being processed, we might increment and decrement `PendingActions` concurrently. We obsevered an assertion failure where `NumActions` was greater than `NumActions`, which was likely caused by this race.
rdar://68024910
---
Also, switch to posix mutex in lmdb. TSan does not support sysv semaphores, so switch to posix mutex. Also,
disable robust mutexes, since we do not support multi-process access to the database anyway.
=> Fix race in index delegate callback 

Package.swift
The Windows C++ runtime requires C++14.  This is handled transparently
when using the `clang-cl` driver, however, when building with s-p-m, the
`clang` driver is used instead.  This requires explicitly bumping
everything to C++14.
=> build: bump C++ standard to 14

Package.swift
Conditionalize the define to use POSIX mutexes to macOS and Linux
targets.  This would be easier to define as non-POSIX, but the package
description does not have the negative check nor a POSIX check.
This requires bumping the tools version to 5.3 to gain access to
Windows.
=> build: disable POSIX mutexes on Windows

Package.swift
This is a run-time dependency inside the tests.  The missing dependency wasn't generally visible when testing from the command-line unless you tried to build+test specific targets.
=> [test] Add missing dependency on tibs executable

include/indexstore/IndexStoreCXX.h
We get rare reports from TSan that there is a race between modifying the
UnitEventInfoDeque and its own destructor. This appears to be caused by
uninstrumented code in the indexstore library as well as the underlying
OS file watching library (FSEvents, inotify, etc.), which prevents TSan
from realizing that the event stream callback and the event stream
finalizer are never called concurrently. We workaround by introducing an
unnecessary mutex that we lock around the requisite calls.
rdar://69514830
=> [tsan] Workaround uninstrumented library code

Sources/IndexStoreDB/IndexStoreDB.swift
There is nothing that requires the use of `MSVCRT`.  Use the modern C
library on Windows, which also helps remove the `visualc` module in the
Swift standard library.
=> IndexStoreDB: use `ucrt` instead of `MSVCRT`

Utilities/build-script-helper.py
I've been running the entire build under Python 3 lately, but I'd get the usual error about mixing strings with bytes if this wasn't set. With this change, no problem building and running the tests.
=> [build-script-helper] make it run under Python 3

include/IndexStoreDB/Index/IndexSystemDelegate.h, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp
This is useful for letting the delegate know how many initial units will be processed after initializing the datastore.
=> [IndexSystemDelegate] Introduce `initialPendingUnits()` callback

Sources/ISDBTibs/TibsToolchain.swift
Treat the `.` separator as part of the extension for shared libraries.
=> ISDBTibs: extract `.` into the extension (NFC)

Sources/ISDBTibs/TibsToolchain.swift
Windows uses an extension for executable files.  Support this to ensure
that we can correctly identify the executables in the TibsToolchain on
Windows.
=> ISDBTibs: add extension for executables

README.md
The markup version of the readme that is displayed for the main page in this repo contains the following bad link:
Status code [404:NotFound] - Link: https://github.com/apple/llvm-project/tree/apple/master/clang/tools/IndexStore
It should be: https://github.com/apple/llvm-project/tree/apple/main/clang/tools/IndexStore
**Extra**
This bad link was found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
Re-check this Repo using the tool’s website: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fapple%2findexstore-db
If this has been helpful, or if you have any feedback on the tool itself, then please feel free to share your thoughts by adding a comment here, or adding to …
=> The README file in this repo has a bad link - [404:NotFound] - "llvm-project"

Sources/ISDBTestSupport/INPUTS/CProject/d.c, Sources/ISDBTestSupport/INPUTS/CProject/d.h, Sources/ISDBTestSupport/INPUTS/CProject/e.c, Sources/ISDBTestSupport/INPUTS/CProject/e.h, Sources/ISDBTestSupport/INPUTS/CProject/project.json, Sources/ISDBTestSupport/INPUTS/SwiftModules/c.swift, Sources/ISDBTestSupport/INPUTS/SwiftModules/project.json, Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/SymbolIndex.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexSystem.cpp, lib/Index/SymbolIndex.cpp
Add a new API which can be used to retrieve a list of symbol definitions or declarations from a file, like so:
```swift
func symbols(inFilePath path: String) -> [Symbol] { /* defined in PR */ }
```
```swift
let symbols = Globals.index.symbols(inFilePath: path)
for symbol in symbols {
print(symbol.name)
}
```
I added integration tests with the guidance of @benlangmuir. These tests withstood mutation testing and caught meaningful errors during the development process.
=> Add  `symbols(inFilePath path: String)`

lib/Index/IndexDatastore.cpp
Cherry-pick https://github.com/apple/indexstore-db/pull/130 to release/5.5
---
We observed such a large unit in practice, so increase our retry limit
so that it can accomodate such a large unit even if it happens to be the
first one registered with the index and has to perform all the doublings
in a row. The goal of the retry limit is not to keep the DB small, but
to abort in the case of a bug causing unlimited growth.
rdar://77288893
=> [5.5] Allow individual units that require a database file > 1 GB

lib/Index/IndexDatastore.cpp
We observed such a large unit in practice, so increase our retry limit
so that it can accomodate such a large unit even if it happens to be the
first one registered with the index and has to perform all the doublings
in a row. The goal of the retry limit is not to keep the DB small, but
to abort in the case of a bug causing unlimited growth.
rdar://77288893
=> Allow individual units that require a database file > 1 GB

Sources/ISDBTibs/Process.swift, Sources/ISDBTibs/TibsBuilder.swift
When there is a failure, include the stdout + stderr if they can be
decoded. This should help track down some failures we're seeing
sporadically in CI.
=> [tibs] Extend error types to include process output

Sources/ISDBTibs/OutputFileMap.swift, Sources/ISDBTibs/TibsBuilder.swift, Sources/ISDBTibs/TibsResolvedTarget.swift, Tests/ISDBTibsTests/TibsCompilationDatabaseTests.swift
We are seeing sporadic test failures after the driver started using
-emit-modules-separately behaviour. For now, workaround by adding -c to
the command to force a per-file compilation. Long term we should figure
out a solution that lets us index and produce swiftmodules without
emitting the unnecessary .o files.
rdar://83215771
=> [tibs] Workaround issue with new -emit-modules-separately behaviour

lib/Database/Database.cpp
Previously it would get truncated to the stored data, meaning we would start using a full database that needs growing.
=> [Database] When opening an existing database make sure to preserve its original size

Tests/IndexStoreDBTests/IndexTests.swift
This is currently failing on Linux CI: https://ci.swift.org/view/Dashboard/job/oss-swift-package-ubuntu-20_04-aarch64/691/
rdar://87728066
=> [tests] Disable a new test thats failing on linux

Sources/ISDBTibs/Makefile.swift
Cherry-pick https://github.com/apple/indexstore-db/pull/141 to release/5.6
rdar://88172057
=> [5.6][ISDBTibs/Makefile] Use `String(contentsOf:encoding:)` which gives the more efficient native String backing

Utilities/build-script-helper.py, Utilities/import-llvm
When running locally, it looks like we just need to change the shebang.
https://github.com/apple/indexstore-db/issues/150
=> Update build-script-helper.py to Python 3

include/llvm/Support/Chrono.h
`Chrono.h` uses `ratio`, but doesn't include its corresponding header.
This is fine on main and on the regular SPM build because `chrono`
includes `ratio` in one of its private headers and main's `chrono` just
exports all the headers. But on rebranch the private headers are now ...
private and thus `ratio` is no longer visible.
Include it directly in `Chrono.h` to unblock rebranch for now.
=> Add missing <ratio> header in "llvm/Support/Chrono.h"

Sources/ISDBTestSupport/INPUTS/HermeticMixedLang/a.swift, Sources/ISDBTestSupport/INPUTS/HermeticMixedLang/bridging-header.h, Sources/ISDBTestSupport/INPUTS/HermeticMixedLang/c.h, Sources/ISDBTestSupport/INPUTS/HermeticMixedLang/c.m, Sources/ISDBTestSupport/INPUTS/HermeticMixedLang/project.json, Sources/ISDBTestSupport/TibsTestWorkspace.swift, Sources/ISDBTibs/TibsBuilder.swift, Sources/IndexStoreDB/IndexStoreDB.swift, Tests/IndexStoreDBTests/IndexTests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, include/indexstore/IndexStoreCXX.h, include/indexstore/indexstore_functions.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexDatastore.h, lib/Index/IndexSystem.cpp, lib/Index/indexstore_functions.def
**Explanation**: https://github.com/apple/llvm-project/pull/4207 adds path remappings
to the index store to allow using hermetic index data but remapping
for local use without the need of any external tools like index-import.
This adds a new prefixMappings parameter to IndexStoreDB.init to allow giving the
prefix mapping to remap from hermetic/canonical --> local paths. If prefix
mappings are given while the new IndexStore API is unavailable,
indexstoredb creation will fail noting that the new API is only
available in newer versions of libIndexStore.
In addition, I've added a new `indexstoredb_creation_options_*` API to
allow configuring options when creating indexstoredb from Swift.
To support testing the remappings, TibsBuilder now supports
replacing arguments containing `$SRC_DIR` and …
=> [5.7] Support for hermetic indexing + path remappings

Utilities/build-script-helper.py
This should contain no functionality change. I just
- added type annotations
- reordered some code into different functions
- changed indentation to 4 space to be consistent with Python scripts in the swift repo
This is a fallout of trying to get sourcekit-lsp and indexstore-db into the unified SwiftPM build.
=> Improvements to build-script-helper.py

.flake8, Utilities/build-script-helper.py
This contains the analogous changes from https://github.com/apple/sourcekit-lsp/pull/597 as well as the following additional ones:
- Add SWIFTCI_USE_LOCAL_DEPS=1 environment variable when invoking SwiftPM
- So far, this has not been relevant because indexstore-db didn’t have any dependencies. Once we build indexstore-db in a unified SwiftPM the `swift build` invocation will also resolve Package.swift for the other packages in the unified build, which need this environment variable.
=> Several changes in build-script-helper.py to support building indexstore-db in a unified build

Sources/ISDBTibs/TibsBuilder.swift
Windows does not have the `touch` command.  Since we are simply creating
an empty file, we can emulate this using `copy NUL $out`.  This is
equivalent to using `cp /dev/null $out` on Unix platforms.  We can now
at least run through the index build part of the SourceKit-LSP test.
=> ISDBTibs: adjust `touch` for Windows

Sources/ISDBTibs/TibsBuilder.swift
Windows requires a SDK to be provided.  The default SDK path is the
location specified by `SDKROOT` in the environment.  Use this value for
the default value.
=> ISDBTibs: honor `SDKROOT` as default SDK

README.md
The README says Clang, which can give the incorrect impression
that -index-store-path is an option in upstream Clang. However,
the index store functionality hasn't been upstreamed yet,
so specifying 'Apple Clang' instead of just 'Clang' makes things
clearer to anyone looking at the README.
=> Mention Apple Clang explicitly in README

lib/Database/lmdb/mdb.c
https://bugs.openldap.org/show_bug.cgi?id=9806 notes MDB_PAGE_FULL can occur for widely varying record sizes (which we definitely have). The size chosen for `nkeys` was for 4KB pages, but M1s (and up) have 16KB pages. For now set this based on the page size of the system, at least until there's an actual fix in LMDB itself.
Resolves rdar://100363010.
=> Tentative fix for MDB_PAGE_FULL errors

Sources/ISDBTestSupport/INPUTS/HermeticMixedLangRelativePaths/a.swift, Sources/ISDBTestSupport/INPUTS/HermeticMixedLangRelativePaths/bridging-header.h, Sources/ISDBTestSupport/INPUTS/HermeticMixedLangRelativePaths/c.h, Sources/ISDBTestSupport/INPUTS/HermeticMixedLangRelativePaths/c.m, Sources/ISDBTestSupport/INPUTS/HermeticMixedLangRelativePaths/project.json, Tests/IndexStoreDBTests/IndexTests.swift, include/IndexStoreDB/Database/ImportTransaction.h, include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Index/StoreUnitInfo.h, lib/Database/ImportTransaction.cpp, lib/Database/ImportTransactionImpl.h, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/FilePathIndex.cpp, lib/Index/FileVisibilityChecker.cpp, lib/Index/IndexDatastore.cpp
Additionally, don't apply the working dir to unit paths, instead we should treat them as verbatim identifiers for the units.
This improves support for build systems such as Bazel where the build/execution root is remapped to ., meaning all paths including unit paths become relative. Previously, this wasn't supported because the unit name internally would be remapped to the absolute path when an index prefix mapping is used, instead of preserving the canonical unit path.
Note that the latest version of libIndexStore already makes paths absolute before writing them, so the only current way to get relative file paths in the index data is with index path mappings.
cc @bnbarham
=> Allow relative file paths during canonicalization

include/IndexStoreDB/Database/ImportTransaction.h, include/IndexStoreDB/Database/ReadTransaction.h, include/IndexStoreDB/Index/StoreUnitInfo.h, lib/Database/ImportTransaction.cpp, lib/Database/ReadTransaction.cpp, lib/Database/ReadTransactionImpl.h, lib/Index/IndexDatastore.cpp
The recent change to out files stored references to stack-allocated strings. Change these to `std::string` instead.
Also do a bunch more renaming to `OutFileIdentifier` while I'm here.
=> Fix dangling references to the stack

Package.swift
This allows us to use `executableTarget` for `tibs`, which resolves an issue when building IndexStoreDB with SourceKit-LSP, as the latter also needs `swift-tools-version` to be updated to 5.5. None of the CI nodes seem to be running anything older than Swift 5.5 for a long time already.
=> Package.swift: bump `swift-tools-version` to 5.5

Sources/IndexStoreDB/IndexStoreDB.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/SymbolIndex.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexSystem.cpp, lib/Index/SymbolIndex.cpp
This will be used by sourcekit-lsp to discover test in https://github.com/apple/sourcekit-lsp/pull/978.
=> Add functions to retrieve all tests within a workspace or within a given source file

lib/Database/CMakeLists.txt
This silences the deprecation warnings to help identify real issues in building LMDB on Windows.
=> lmdb: silence some deprecation warnings on Windows

lib/Database/lmdb/COPYRIGHT, lib/Database/lmdb/lmdb++.h, lib/Database/lmdb/lmdb.h, lib/Database/lmdb/mdb.c
Summary of interesting changes:
* Windows compilation fixes
* Fix for errant MDB_PAGE_FULL on mdb_put which could happen when records had non-uniform sizes (this is the upstream patch for the fix in 6417ff85761b46ea67d4041e088526aa9d7d7726)
* Alignment fix for SPARC (probably doesn't impact us)
* Fix for replacing values with MDB_DUPSORT leading to a broken database
=> [lmdb] Update LMDB to latest upstream

Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/Symbol.swift, Tests/IndexStoreDBTests/IndexTests.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/StoreUnitInfo.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FilePathIndex.cpp, lib/Index/IndexDatastore.cpp
This will be used by sourcekit-lsp’s cross-file rename.
=> Add API to get the language in which a symbol is defined and the symbol provider for a source file

include/IndexStoreDB/Index/IndexSystemDelegate.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexDatastore.cpp, lib/Index/IndexSystem.cpp
Remove `DependentUnitOutOfDateTriggerHint`, and collapse the class hierarchy into a single class `OutOfDateFileTrigger`, which stores both the file name as well as the mod time. Then, change the `OutOfDateTriggers` map in UnitMonitor to use StringRef keys. This significantly reduces memory consumption for large projects. We could likely go further here by eliminating the storing of triggers completely, but I'm leaving that as future work for now.
rdar://50929788
=> Reduce memory consumption for OutOfDateTriggerHints

lib/Index/IndexSystem.cpp
Avoid moving `unitInfo` in the body of the `for` loop here.
=> Avoid a potential use-after-move

include/llvm/ADT/Triple.h, lib/LLVMSupport/Support/Triple.cpp
Cherry-pick the visionOS target changes in https://github.com/apple/llvm-project/commit/7d3466b5c30878c5e014949ebf1dc44bb2160995.
rdar://125113602
=> Add LLVM target support for visionOS

include/llvm/ADT/Triple.h, lib/LLVMSupport/Support/Triple.cpp
*6.0 cherry-pick of https://github.com/apple/indexstore-db/pull/183*
- Explanation: Add support for visionOS targets to indexstore-db's copy of LLVM
- Scope: N/A
- Issue: rdar://125113602
- Risk: Low
- Testing: N/A
- Reviewer: Ben Barham
=> [6.0] Add LLVM target support for visionOS

Sources/IndexStoreDB/Symbol.swift
* **Explanation**: https://github.com/apple/sourcekit-lsp/pull/1166 creates a dictionary with `Symbol` as a key, which requires `Symbol` to conform to `Hashable`
* **Scope**: Adding `Hashable` conformance to `Symbol`
* **Risk**: Very low, just adding a protocol conformance
* **Testing**: Verified that `Symbol` can be used as a dictionary key with this change
* **Issue**: n/a
* **Reviewer**:  @bnbarham on https://github.com/apple/indexstore-db/pull/187
=> [6.0] Make `Symbol` conform to `Hashable`

lib/CIndexStoreDB/CIndexStoreDB.cpp
The doc comment said that the timestamp was in seconds, but we were returning a timestamp in nanoseconds.
=> Return timestamp of latest unit for file in seconds not nanoseconds

lib/CIndexStoreDB/CIndexStoreDB.cpp
* **Explanation**: We were incorrectly returning a timestamp as nanoseconds instead of seconds in `indexstoredb_timestamp_of_latest_unit_for_file`
* **Scope**: The `indexstoredb_timestamp_of_latest_unit_for_file` function introduced a few weeks ago that doesn’t  have any users yet
* **Risk**: Very low, the function hasn’t been used so far
* **Testing**: Tested that this fixes an issue I was seeing in SourceKit-LSP
* **Issue**: n/a
* **Reviewer**:  @bnbarham on https://github.com/apple/indexstore-db/pull/190
=> [6.0] Return timestamp of latest unit for file in seconds not nanoseconds

Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/SymbolLocation.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
=> Make `indexstoredb_symbol_location_timestamp` and `indexstoredb_timestamp_of_latest_unit_for_file` return nanoseconds instead of seconds

lib/CIndexStoreDB/CIndexStoreDB.cpp
An incorrect cherry-pick caused us to device the nanoseconds twice by 1.000.000.000, when we should only divide it once.
This makes the state of `release/6.0` match `main`.
=> Fix issue that converted a unix timestamp to from nanoseconds to seconds twice

Sources/IndexStoreDB/SymbolProperty.swift, Sources/IndexStoreDB/SymbolRole.swift
This allows us to build the `SourceKitLSP` module in Swift 6 mode.
=> Mark `SymbolProperty` and `SymbolRole` as `Sendable`

Sources/IndexStoreDB/IndexStoreDB.swift
These functions don’t actually let the body escape. We should not need to mark `body` as `@escaping` and should use `withoutActuallyEscaping` in the implementation.
rdar://126803786
=> Mark the closures to the `forEach` functions as non-escaping

Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/SymbolOccurrence.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/StoreUnitInfo.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/FilePathIndex.cpp, lib/Index/IndexDatastore.cpp
This reverts commit a335a473dc2cd79edfb1f025b72f815f11df97a2.
The API is no longer needed.
=> Revert "Allow retrieval of the symbol provider kind for a source file"

Sources/ISDBTestSupport/TestLocation.swift, Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/Symbol.swift, Sources/IndexStoreDB/SymbolOccurrence.swift, Tests/IndexStoreDBTests/IndexTests.swift, include/CIndexStoreDB/CIndexStoreDB.h, lib/CIndexStoreDB/CIndexStoreDB.cpp
- **Explanation**: Adds a new API to get the symbol provider of a `SymbolOccurrence `
- **Scope**: Adds new API
- **Risk**: Low, purely additive
- **Testing**: Tested in SourceKit-LSP
- **Issue**: n/a
- **Reviewer**:   @bnbarham on https://github.com/apple/indexstore-db/pull/200
=> [6.0] Expose the symbol provider of a SymbolOccurrence via the Swift API

.gitignore, Sources/IndexStoreDB/IndexStoreDB.swift, include/CIndexStoreDB/CIndexStoreDB.h, include/IndexStoreDB/Index/IndexSystem.h, include/IndexStoreDB/Index/SymbolDataProvider.h, include/IndexStoreDB/Index/SymbolIndex.h, lib/CIndexStoreDB/CIndexStoreDB.cpp, lib/Index/IndexSystem.cpp, lib/Index/StoreSymbolRecord.cpp, lib/Index/StoreSymbolRecord.h, lib/Index/SymbolIndex.cpp
adds a method `symbolOccurrences(inFilePath:)` that returns all symbol occurrences within a source file.
=> Symbol occurrences in file

CODEOWNERS
No longer have write access to the repo, which makes CODEOWNERS invalid.
=> Remove Argyrios and Ben Langmuir as code owners

Sources/IndexStoreDB/IndexStoreDB.swift
This was recently added in swiftlang/swift#72161 and swiftlang/swift#72634. I've been building it with this patch on my daily Android CI since then, finagolfin/swift-android-sdk#151, and natively on Android too.
@ahoppen, should be a quick review.
=> Import new Android overlay

Sources/IndexStoreDB/IndexStoreDB.swift
__Explanation:__ Now that this new overlay was merged into the 6.0 compiler too in swiftlang/swift#74758, this adds the Bionic module from the overlay to the one file that currently adds `import Glibc`.
__Scope:__ Add import on Android only
__Issue:__ None
__Original PR:__ #211 and #213
__Risk:__ None
__Testing:__ Passed all CI on trunk, plus on my daily Android CI, finagolfin/swift-android-sdk#151
__Reviewer:__ @ahoppen
@bnbarham, easy review.
=> [6.0] Import Bionic module from new Android overlay

lib/Support/Logging-Mac.mm
Previously we were using `NSLog`'s `%s` specifier, but that uses the default system encoding instead of UTF-8. Convert to NSString to ensure we can handle UTF-8 log messages.
rdar://131747774
=> Ensure macOS logging uses UTF-8

lib/Support/Logging-Mac.mm
*6.0 cherry-pick of #214*
- Explanation: Fixes macOS logging to support UTF-8
- Scope: Affects logging on macOS
- Issue: rdar://131747774
- Risk: Low, only affects logging
- Testing: Verified locally
- Reviewer: Ben Barham
=> [6.0] Ensure macOS logging uses UTF-8

Sources/IndexStoreDB/SymbolRole.swift, include/CIndexStoreDB/CIndexStoreDB.h
This was previously miscompiling with clang (would be 32 bit instead of
64 bit) and now errors with clang 19. Note that this doesn't seem to
have had any impact within indexstore-db itself - the C++ side is
using a different enum (`SymbolRole`) which has:
```
Canonical = uint64_t(1) << 63,
```
And seems like the only real use of `Canonical` is
`foreachCanonicalSymbolOccurrenceImpl` itself (also C++).
=> Add size for indexstoredb_symbol_role_t

lib/Database/Database.cpp
`llvm::sys::fs::rename` cannot rename directories becasue it creates a file handle for the file to rename, which doesn't work for directories. Implement a custom rename function that uses `MoveFileW` on Windows. 
Fixes https://github.com/swiftlang/sourcekit-lsp/issues/1750
=> Fix issue that caused database rename to and from `saved` to fail

lib/Database/Database.cpp
I don't know why but using `llvm::sys::fs::remove_directories` to delete the directories sometimes does not actually delete the directory, which causes `MoveFileW` to fail because the destination already exists. I don't see this issue when using `RemoveDirectoryW`
=> On Windows use `RemoveDirectoryW` to delete empty directory before renaming directory to it

Utilities/build-script-helper.py
Building indexstore-db with ubsan enabled with an Xcode 15.1 SDK causes C++ exception to not be catchable with `try {} catch {}` blocks and indexstore-db relies on exception catching, possibly related to  https://stackoverflow.com/questions/51673343/clang-with-libc-exceptions.
Disable UBSAN for now and re-enable it when CI nodes has been updated to Xcode 16.
=> Disable UBSAN on macOS

Sources/ISDBTibs/TibsToolchain.swift
I need this patch with Swift 6 when compiling sourcekit-lsp natively on Android.
=> Import new Android overlay again

Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB_CIndexStoreDB/CIndexStoreDB.cpp, Sources/IndexStoreDB_CIndexStoreDB/include/IndexStoreDB_CIndexStoreDB/CIndexStoreDB.h, Sources/IndexStoreDB_Index/include/IndexStoreDB_Index/IndexStoreCXX.h
- Make `PathMapping` equatable
- Allow creation of a Swift `IndexStoreDB` instance from an existing C++ `IndexSystem` type
- Support getting the prefix map from `IndexStoreCreationOptions`
=> A few miscellaneous updates

Sources/IndexStoreDB_Index/SymbolIndex.cpp
Check if we weren't able to find a visible provider for the file and if not, continue checking other provider codes.
=> Avoid crash when querying in non-visible files

Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB_CIndexStoreDB/CIndexStoreDB.cpp, Sources/IndexStoreDB_CIndexStoreDB/include/IndexStoreDB_CIndexStoreDB/CIndexStoreDB.h, Sources/IndexStoreDB_Index/IndexDatastore.cpp, Sources/IndexStoreDB_Index/IndexDatastore.h, Sources/IndexStoreDB_Index/IndexSystem.cpp, Sources/IndexStoreDB_Index/include/IndexStoreDB_Index/IndexSystem.h
We can call this from SourceKit-LSP when the indexing process has finished to ensure that we import the new unit into indexstore-db before declaring indexing done.
=> Add function to explicitly import a unit

Package.swift, Sources/IndexStoreDB_LLVMSupport/include/IndexStoreDB_LLVMSupport/llvm_Config_config.h, Utilities/import-llvm.d/include/llvm/Config/config.h
Fix building on FreeBSD
- adjust llvm config headers accordingly
- `sark` is removed on aarch64 FreeBSD
- link against `execinfo` for test
=> [FreeBSD] fix building on FreeBSD

Sources/IndexStoreDB/IndexDelegate.swift, Sources/IndexStoreDB/IndexStoreDB.swift, Sources/IndexStoreDB/IndexStoreDBError.swift, Sources/IndexStoreDB/SymbolOccurrence.swift
Several structs already declared Sendable conformance. This PR adds support to (most of) the remaining ones.
- `SymbolOccurrence` and `SymbolRelation` are easy and safe changes.
- `IndexStoreDBError`, `PathMapping`, and `StoreUnitInfo` are similar, but I don't know if this change is what you had in mind, @ahoppen.
Less safe changes:
- `IndexDelegate` can be useful to wrap in a Swift actor, so I'd _like_ to mark this as Sendable, but am unsure if this is wise, given there's mention of asynchronous behavior within that protocol.
- `IndexStoreDB` contains an `UnsafeMutableRawPointer` so the best that we can do (with what I'm aware of) is `@unchecked Sendable`.
Reviewers: Please let me know if any of these changes should be adjusted and/or how we might test this beyond visual inspection. …
=> Adopt Sendability in Remaining Models

Package.swift
Update the dependant packages to match 6.2.1, so parent
dependencies like sourcekit-lsp will not have version errors
=>  Update dependant packages to match 6.2.1 branch
